# system config

export CONFIG_DIR="$(cd $(dirname "${BASH_SOURCE[0]}"); pwd)/config"
export DOWNLOAD_DIR="/volume1/Data"
export DOCKER_GROUP_ID=100

# app specific config

export CADDY_HTTP_PORT=8888
export CADDY_HTTPS_PORT=8887

export DELUGE_DAEMON_PORT=58846
export DELUGE_WEBUI_PORT=8112
export DELUGE_BITTORRENT_PORT=8998

export DELUGEVPN_DAEMON_PORT=58846
export DELUGEVPN_WEBUI_PORT=8112
export DELUGEVPN_BITTORRENT_PORT=8998
export DELUGEVPN_PRIVOXY_PORT=8118
export DELUGEVPN_VPN_PROVIDER="pia"
export DELUGEVPN_VPN_REMOTE="ca-toronto.privateinternetaccess.com"
export DELUGEVPN_VPN_USER="p420"
export DELUGEVPN_VPN_PASSWD="420blazeit"
export DELUGEVPN_LAN_SUBNET="192.168.1.0/24"

export FLEXGET_PORT=5050
export FLEXGET_TORRENT_PLUGIN="deluge"
export FLEXGET_WEB_PASSWD="420blazeit"

export MUMBLE_PORT=64738

export NZBGET_WEBUI_PORT=6789

export SALIEN_TOKEN="123acbdef"

export SONARR_PORT=8989

export SWFSRV_PORT=8700
